#!/usr/bin/env bash

# We need to add /opt/amdgpu-pro/lib/x86_64-linux-gnu to the linker configuration
# We added the path with a /etc/ld.so.conf.d config file, and we mounted /opt/amdgpu-pro
# in the Docker command line, now run ldconfig.
ldconfig


GENERATE_TO=${EQB_ADDRESS:-"tq1qwc2y5886d4z90yt0ecapx58gsl6h5fufcamxq4"}
GRAFFITI=${COINBASE_SIG:-"BFG inside Docker"}
NODE=${NODE_ADDRESS:-"http://localhost:18331"}

echo GENERATE TO: ${GENERATE_TO}
echo GRAFFITI: ${GRAFFITI}
echo NODE: ${NODE}

bfgminer -u equibit -p equibit --generate-to "${GENERATE_TO}" --coinbase-sig "${GRAFFITI}" -D -o "${NODE}" --no-default-config -S auto
